### ISSUE TITLE
NPC's do not save

### ISSUE THREAD

**Issue by laserrrrr** [Scroojalix/NPCManager#14]
When the server is restarted all NPC's are erased.

**Comment by Scroojalix** [comment]
I can't seem to replicate the issue. Could you please give me some more information.

- server version
- server software (spigot, paper, etc)
- storage method (in config.yml)
- any error messages in the console
- version of java that the server is running (if possible)
- anything else you think is relevant.

**Comment by Scroojalix** [comment]
Nevermind, I realise the issue. I fixed this bug a while ago but forgot to release a new version. I'll release one shortly.

**Comment by Scroojalix** [comment]
Version 1.4.4 has been released. It should address this issue.
https://github.com/Scroojalix/NPCManager/releases/latest

**Comment by laserrrrr** [comment]
Awesome, thank you so much! I appreciate it :)
