### ISSUE TITLE
Model Data and Enchants don't save on server reset

### ISSUE THREAD

**Issue by laserrrrr** [Scroojalix/NPCManager#17]
Sorry for another report, but I found that when I restart the server, all my NPC's equipment get stripped of their enchants and custom model data.

**Comment by Scroojalix** [comment]
No worries, thanks for the report. Finding and reporting bugs is always appreciated.
Anyways, this should now be fixed. Just head over to
https://github.com/Scroojalix/NPCManager/releases/tag/v1.5.0
and download the latest release. Note that you may have to set the NPC's equipment again as the way in which NPC equipment is serialised has changed.

**Comment by laserrrrr** [comment]
Awesome, thanks a bunch :D
